### ISSUE TITLE
"SceneKit Scene.scn" file is missing

### ISSUE THREAD

**Issue by adamnemecek** [ziyaointl/Fourier#2]
Hey,
this looks like a cool project. 

When I tried to build it on my machine I get an error that "SceneKit Scene.scn" file is missing. 

Could you please add it? I'd love to check this out.

Thanks,
Adam

**Comment by ziyaointl** [comment]
Hi @adamnemecek 

I updated the resource list to remove the SceneKit Scene.scn requirement. Now the project should compile. Please note that I used the xcode project only for prototyping so it is very different from the final version. If you want to check out my code, I highly recommend looking into the Fourier.playgroundbook folder instead. To run it, simply airdrop Fourier.playgroundbook to an iPad and open it with the Swift Playgrounds app. If you have any more questions, please let me know!

Cheers,
Ziyao
